// GENERATED by scripts/fetch-photos.ts — do not edit by hand.
import type { PhotoMeta } from '../engine/types';

export const photos: Record<string, PhotoMeta> = {
  "abies-alba": {
    "file": "abies-alba.webp",
    "author": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abies_alba_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-001.jpg"
  },
  "abies-pinsapo": {
    "file": "abies-pinsapo.webp",
    "author": "Por los caminos de Málaga",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abies_pinsapo_Pinsapar_de_Froncaire_1.jpg"
  },
  "acer-campestre": {
    "file": "acer-campestre.webp",
    "author": "Willow",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acer_campestre_006.jpg"
  },
  "acer-monspessulanum": {
    "file": "acer-monspessulanum.webp",
    "author": "Fritz Geller-Grimm",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acer_monspessulanum_fg02.jpg"
  },
  "acer-negundo": {
    "file": "acer-negundo.webp",
    "author": "Matt Lavin from Bozeman, Montana, USA",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acer_negundo_Bozeman_1.jpg"
  },
  "acer-platanoides": {
    "file": "acer-platanoides.webp",
    "author": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020_year._Herbarium._Acer_platanoides._img-012.jpg"
  },
  "acer-pseudoplatanus": {
    "file": "acer-pseudoplatanus.webp",
    "author": "Christian Pirkl",
    "license": "CC BY-SA 3.0 at",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ID_1211_Bergahorn_0011.jpg"
  },
  "acer-saccharinum": {
    "file": "acer-saccharinum.webp",
    "author": "renee_mcgurk",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acer_saccharinum_Grimes_Farm_1.jpg"
  },
  "aesculus-hippocastanum": {
    "file": "aesculus-hippocastanum.webp",
    "author": "Stephan van Helden",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ND_678.N.59_Hofers_Kastanien_in_Wettringen.jpg"
  },
  "ailanthus-altissima": {
    "file": "ailanthus-altissima.webp",
    "author": "Darkone (talk · contribs)",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:G%C3%B6tterbaum_(Ailanthus_altissima).jpg"
  },
  "albizia-julibrissin": {
    "file": "albizia-julibrissin.webp",
    "author": "Cmapm",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albizzia_julibrissin_in_Sevastopol_1.jpg"
  },
  "alnus-glutinosa": {
    "file": "alnus-glutinosa.webp",
    "author": "Willow",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alnus_glutinosa_011.jpg"
  },
  "amelanchier-ovalis": {
    "file": "amelanchier-ovalis.webp",
    "author": "No machine-readable author provided. Victor M. Vicente Selvas assumed (based on copyright claims).",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Amelanchier_ovalis.JPG"
  },
  "anagyris-foetida": {
    "file": "anagyris-foetida.webp",
    "author": "Vojtěch Zavadil",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:4150-Anagyris_foetida-Gargano-5.06.JPG"
  },
  "araucaria-araucana": {
    "file": "araucaria-araucana.webp",
    "author": "Vicente Fernández Rioja",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Araucaria_en_Parque_Nacional_Conguillio.jpg"
  },
  "araucaria-heterophylla": {
    "file": "araucaria-heterophylla.webp",
    "author": "bertknot from scarborough, australia",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Araucaria_heterophylla_Norfolk_Island_0.jpg"
  },
  "arbutus-unedo": {
    "file": "arbutus-unedo.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Arbouse.jpg"
  },
  "betula-pendula": {
    "file": "betula-pendula.webp",
    "author": "Percita at Flickr",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Betula_pendula_Finland.jpg"
  },
  "betula-pubescens": {
    "file": "betula-pubescens.webp",
    "author": "Elfo del bosque",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abedulpubescente.jpg"
  },
  "brachychiton-populneus": {
    "file": "brachychiton-populneus.webp",
    "author": "Philmarin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:B._populneus_flor-1.JPG"
  },
  "carpinus-betulus": {
    "file": "carpinus-betulus.webp",
    "author": "Botaurus",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brohmer-Berge-Rothem%C3%BChl-24-10-2009-30.jpg"
  },
  "castanea-sativa": {
    "file": "castanea-sativa.webp",
    "author": "JLPC",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Romagne_86_Ch%C3%A2taignes_2008.jpg"
  },
  "catalpa-bignonioides": {
    "file": "catalpa-bignonioides.webp",
    "author": "Zeynel Cebeci",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Catalpa_bignonioides_05.jpg"
  },
  "cedrus-atlantica": {
    "file": "cedrus-atlantica.webp",
    "author": "Nikos D. Karabelas",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moroccan_Atlantic_cedar.jpg"
  },
  "cedrus-deodara": {
    "file": "cedrus-deodara.webp",
    "author": "Paul Evans from London, United Kingdom",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cedrus_deodara_Manali_2.jpg"
  },
  "cedrus-libani": {
    "file": "cedrus-libani.webp",
    "author": "Olivier BEZES",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:C%C3%A8dre_du_Liban_Barouk_2005.jpg"
  },
  "celtis-australis": {
    "file": "celtis-australis.webp",
    "author": "Luis Fernández García",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Celtis_australis_20150404_a.jpg"
  },
  "ceratonia-siliqua": {
    "file": "ceratonia-siliqua.webp",
    "author": "Eduardo Milla",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Algarrobo_m%C3%BAltiple.jpg"
  },
  "cercis-siliquastrum": {
    "file": "cercis-siliquastrum.webp",
    "author": "Zeynel Cebeci",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cercis_siliquastrum_-_Judas_tree_-_Erguvan_01.jpg"
  },
  "chamaerops-humilis": {
    "file": "chamaerops-humilis.webp",
    "author": "tato grasso",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chamaerops_humilis_(Zingaro)015.jpg"
  },
  "citrus-aurantium": {
    "file": "citrus-aurantium.webp",
    "author": "Zeynel Cebeci",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Turun%C3%A7_-_Citrus_aurantium_02.JPG"
  },
  "corylus-avellana": {
    "file": "corylus-avellana.webp",
    "author": "MPF",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Corylus_avellana_shrub.jpg"
  },
  "corylus-colurna": {
    "file": "corylus-colurna.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TurkHazel.jpg"
  },
  "cotinus-coggygria": {
    "file": "cotinus-coggygria.webp",
    "author": "LIght Dim",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%BA%D1%83%D0%BC%D0%BF%D0%B8%D1%8F_%D0%BA%D0%BE%D0%B6%D0%B5%D0%B2%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_European_smoketree_(Cotinus_coggygria).jpg"
  },
  "crataegus-laevigata": {
    "file": "crataegus-laevigata.webp",
    "author": "Sten Porse",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Crataegus_laevigata-flowers.jpg"
  },
  "crataegus-monogyna": {
    "file": "crataegus-monogyna.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Crataegus_monogyna_-_Common_hawthorn.jpg"
  },
  "cryptomeria-japonica": {
    "file": "cryptomeria-japonica.webp",
    "author": "Yosemite",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jhomonsugi_in_Yaku_Island_Japan_001.JPG"
  },
  "cupressus-arizonica": {
    "file": "cupressus-arizonica.webp",
    "author": "myself",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chiricahua_Nima1.JPG"
  },
  "cupressus-macrocarpa": {
    "file": "cupressus-macrocarpa.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lone_cypress_in_17-mile-drive.jpg"
  },
  "cupressus-sempervirens": {
    "file": "cupressus-sempervirens.webp",
    "author": "Taoujouti Abdelmouhaïmen",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cypr%C3%A8s.jpg"
  },
  "cydonia-oblonga": {
    "file": "cydonia-oblonga.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cydonia.jpg"
  },
  "erica-arborea": {
    "file": "erica-arborea.webp",
    "author": "Zidat",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Axlen%C7%A7_s_ule%C7%A7%C7%A7ig.jpg"
  },
  "eriobotrya-japonica": {
    "file": "eriobotrya-japonica.webp",
    "author": "muffinn from Worcester, UK",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portugal_-_Algarve_-_Barao_de_Sao_Joao_-_Ann_scrumping_loquats_(25187478424).jpg"
  },
  "eucalyptus-globulus": {
    "file": "eucalyptus-globulus.webp",
    "author": "Murray Fagg",
    "license": "CC BY 3.0 au",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eucalyptus_globulus_globulus_buds.jpg"
  },
  "fagus-sylvatica": {
    "file": "fagus-sylvatica.webp",
    "author": "Malene Thyssen",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grib_skov.jpg"
  },
  "fagus-sylvatica-f-purpurea": {
    "file": "fagus-sylvatica-f-purpurea.webp",
    "author": "Tortuosa",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:FagusPurpurea052005.jpg"
  },
  "ficus-carica": {
    "file": "ficus-carica.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Illustration_Ficus_carica0.jpg"
  },
  "ficus-elastica": {
    "file": "ficus-elastica.webp",
    "author": "VuThiAnh",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Da_bup_do.jpg"
  },
  "ficus-macrophylla": {
    "file": "ficus-macrophylla.webp",
    "author": "User DO'Neil on en.wikipedia",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moretonbayfigfrom1850.JPG"
  },
  "fraxinus-angustifolia": {
    "file": "fraxinus-angustifolia.webp",
    "author": "Luis Fernández García",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fraxinus-angustifolia-20190413a.jpg"
  },
  "fraxinus-excelsior": {
    "file": "fraxinus-excelsior.webp",
    "author": "Willow",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fraxinus_excelsior_001.jpg"
  },
  "fraxinus-ornus": {
    "file": "fraxinus-ornus.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Fraxinus_ornus_-_Flowers_-_Fronton_(Haute-Garonne).jpg"
  },
  "ginkgo-biloba": {
    "file": "ginkgo-biloba.webp",
    "author": "EecherplazGinkgo06.jpg: Cayambe\nderivative work: Ginkgotree (talk)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:GINKGOBAUM-2.jpg"
  },
  "grevillea-robusta": {
    "file": "grevillea-robusta.webp",
    "author": "MargaretRDonald",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grevillearobusta40181608300_6dbb4fe9b0_o.jpg"
  },
  "jacaranda-mimosifolia": {
    "file": "jacaranda-mimosifolia.webp",
    "author": "Kahuroa",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jacaranda1212.jpg"
  },
  "juglans-regia": {
    "file": "juglans-regia.webp",
    "author": "Böhringer Friedrich",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juglans_regia_Echte_Walnussfrucht_1.jpg"
  },
  "juniperus-communis": {
    "file": "juniperus-communis.webp",
    "author": "Ivar Leidus",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juniperus_communis_fruits_-_Keila.jpg"
  },
  "juniperus-oxycedrus": {
    "file": "juniperus-oxycedrus.webp",
    "author": "Jean Tosti",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cade1.jpg"
  },
  "juniperus-phoenicea": {
    "file": "juniperus-phoenicea.webp",
    "author": "Júlio Reis (Tintazul)",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juniperus_phoenicea_berries.jpg"
  },
  "juniperus-sabina": {
    "file": "juniperus-sabina.webp",
    "author": "Meneerke bloem",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juniperus_sabina_01.JPG"
  },
  "juniperus-thurifera": {
    "file": "juniperus-thurifera.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 2.1 es",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juniperus-thurifera-01.jpg"
  },
  "koelreuteria-paniculata": {
    "file": "koelreuteria-paniculata.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Koelreuteria_paniculata_-_inflorescences_and_fruits_-_Palais_Niel.jpg"
  },
  "lagerstroemia-indica": {
    "file": "lagerstroemia-indica.webp",
    "author": "Gabriel Collares",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Extremosa_(Lagerstroemia_indica)_em_um_fim_de_tarde_em_Bag%C3%A9-RS.jpg"
  },
  "laurus-nobilis": {
    "file": "laurus-nobilis.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Laurier.jpg"
  },
  "ligustrum-lucidum": {
    "file": "ligustrum-lucidum.webp",
    "author": "Taken by Fanghong",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:FloweringLigustrumLucidumTree.jpg"
  },
  "liquidambar-styraciflua": {
    "file": "liquidambar-styraciflua.webp",
    "author": "Luis Fernández García",
    "license": "CC BY-SA 2.5 es",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liquidambar-otonno-20071028-1.jpg"
  },
  "liriodendron-tulipifera": {
    "file": "liriodendron-tulipifera.webp",
    "author": "Jean-Pol GRANDMONT",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liriodendron_tulipifera_JPG5a.jpg"
  },
  "magnolia-grandiflora": {
    "file": "magnolia-grandiflora.webp",
    "author": "DavetheMage",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Magnolia_flower_Duke_campus.jpg"
  },
  "malus-domestica": {
    "file": "malus-domestica.webp",
    "author": "W.carter",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tree_with_red_apples_in_Barkedal_4.jpg"
  },
  "melia-azedarach": {
    "file": "melia-azedarach.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chinaberry1216.JPG"
  },
  "mespilus-germanica": {
    "file": "mespilus-germanica.webp",
    "author": "Mel Etitis",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Medlar_blossom.JPG"
  },
  "morus-alba": {
    "file": "morus-alba.webp",
    "author": "GerardM",
    "license": "CC BY-SA 2.1 es",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Morus-alba.jpg"
  },
  "morus-nigra": {
    "file": "morus-nigra.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Illustration_Morus_nigra0.jpg"
  },
  "myrtus-communis": {
    "file": "myrtus-communis.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Illustration_Myrtus_communis0.jpg"
  },
  "nerium-oleander": {
    "file": "nerium-oleander.webp",
    "author": "Alvesgaspar",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nerium_oleander_flowers_leaves.jpg"
  },
  "olea-europaea": {
    "file": "olea-europaea.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:El_Perell%C3%B3_-_Old_olive_tree.jpg"
  },
  "parkinsonia-aculeata": {
    "file": "parkinsonia-aculeata.webp",
    "author": "Forest &amp; Kim Starr",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Starr_010209-0260_Parkinsonia_aculeata.jpg"
  },
  "paulownia-tomentosa": {
    "file": "paulownia-tomentosa.webp",
    "author": "Jean-Pol GRANDMONT",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paulownia_tomentosa_JPG2a.jpg"
  },
  "phillyrea-angustifolia": {
    "file": "phillyrea-angustifolia.webp",
    "author": "Xemenendura",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phillyrea_angustifolia_3.JPG"
  },
  "phillyrea-latifolia": {
    "file": "phillyrea-latifolia.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phillyrea_latifolia.jpg"
  },
  "phoenix-canariensis": {
    "file": "phoenix-canariensis.webp",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoenix_canariensis_kz01.jpg"
  },
  "phoenix-dactylifera": {
    "file": "phoenix-dactylifera.webp",
    "author": "EJ Burns",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoenix_dactylifera_-_EJ_Burns_-_606494286.jpeg"
  },
  "photinia-fraseri": {
    "file": "photinia-fraseri.webp",
    "author": "Famartin",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020-05-07_17_00_21_New_leaves_and_flowers_on_a_Red_Tip_Photinia_along_Ladybank_Lane_in_the_Chantilly_Highlands_section_of_Oak_Hill,_Fairfax_County,_Virginia.jpg"
  },
  "picea-abies": {
    "file": "picea-abies.webp",
    "author": "Ivar Leidus",
    "license": "CC BY-SA 3.0 ee",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kuusk_Keila-Paldiski_rdt_%C3%A4%C3%A4res.jpg"
  },
  "pinus-canariensis": {
    "file": "pinus-canariensis.webp",
    "author": "Tanja Freibott",
    "license": "CC BY-SA 3.0 es",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Caldera_de_Taburiente_(La_Palma,_Islas_Canarias,_Espa%C3%B1a)_03.JPG"
  },
  "pinus-cembra": {
    "file": "pinus-cembra.webp",
    "author": "Tigerente at German Wikipedia",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zirbe01.jpg"
  },
  "pinus-halepensis": {
    "file": "pinus-halepensis.webp",
    "author": "spacebirdy(also known as geimfyglið (:&gt; )=| made with Sternenlaus-spirit)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Calanques_--_Calanque_de_Port_Pin_-_Pinus_halepensis.jpg"
  },
  "pinus-nigra": {
    "file": "pinus-nigra.webp",
    "author": "Karl Gruber",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schwarzkiefer.jpg"
  },
  "pinus-pinaster": {
    "file": "pinus-pinaster.webp",
    "author": "Livioandronico2013",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_pinea_and_ruins_on_Palatine_Hill.jpg"
  },
  "pinus-pinea": {
    "file": "pinus-pinea.webp",
    "author": "Livioandronico2013",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_pinea_and_ruins_on_Palatine_Hill.jpg"
  },
  "pinus-radiata": {
    "file": "pinus-radiata.webp",
    "author": "dalvenjah on Flickr",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_radiata_BigSur.jpg"
  },
  "pinus-sylvestris": {
    "file": "pinus-sylvestris.webp",
    "author": "Hello, I am Bruce on Flickr",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_sylvestris_Glenmuick.jpg"
  },
  "pinus-uncinata": {
    "file": "pinus-uncinata.webp",
    "author": "Joan Simon from Barcelona, España",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_uncinata_(15265252158).jpg"
  },
  "pistacia-lentiscus": {
    "file": "pistacia-lentiscus.webp",
    "author": "Giuseppe Frizzi",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dettaglio_-_Anacardiaceae_Pistacia_lentiscus_Lin._Erbario_Frizzi_Perugia_n._3752.jpg"
  },
  "pistacia-terebinthus": {
    "file": "pistacia-terebinthus.webp",
    "author": "Jean Housen",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20090729_parnonas10.jpg"
  },
  "platanus-hispanica": {
    "file": "platanus-hispanica.webp",
    "author": "Arbres d'ornement-2 - ornamental trees in colour - Public domain book illustration (visual explanation, informative drawing, plate) from Larousse du XXème siècle 1932.jpg https://www.flickr.com/photos/149521109@N03/31052984252//31196536225/",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:London_Plane_Larousse_Extracted.png"
  },
  "platycladus-orientalis": {
    "file": "platycladus-orientalis.webp",
    "author": "yeowatzup at Flickr",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Platycladus_orientalis_Simatai.jpg"
  },
  "populus-alba": {
    "file": "populus-alba.webp",
    "author": "Jakub Hałun",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Populus_alba,_Czajecice,_20060812_1358.jpg"
  },
  "populus-canadensis": {
    "file": "populus-canadensis.webp",
    "author": "AnRo0002",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20140316Pappel2.jpg"
  },
  "populus-nigra": {
    "file": "populus-nigra.webp",
    "author": "No machine-readable author provided. JoJan assumed (based on copyright claims).",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Populus_nigra.Italica.01.jpg"
  },
  "populus-simonii": {
    "file": "populus-simonii.webp",
    "author": "Alain Gérard",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Populus_simonii_Toulouse_18-08-2008.jpg"
  },
  "populus-tremula": {
    "file": "populus-tremula.webp",
    "author": "Øyvind Holmstad",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ospeholt_i_Hurdal.JPG"
  },
  "prunus-armeniaca": {
    "file": "prunus-armeniaca.webp",
    "author": "Fir0002",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apricots.jpg"
  },
  "prunus-avium": {
    "file": "prunus-avium.webp",
    "author": "MPF",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prunus_avium_fruit.jpg"
  },
  "prunus-cerasifera": {
    "file": "prunus-cerasifera.webp",
    "author": "AnRo0002",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20140317Prunus_cerasifera_Hockenheimer_Rheinbogen5.jpg"
  },
  "prunus-cerasus": {
    "file": "prunus-cerasus.webp",
    "author": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prunus_cerasus_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-113.jpg"
  },
  "prunus-domestica": {
    "file": "prunus-domestica.webp",
    "author": "YAMAMAYA",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fruits_Prunus_domestica.jpg"
  },
  "prunus-dulcis": {
    "file": "prunus-dulcis.webp",
    "author": "Ivar Leidus",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Almonds_-_in_shell,_shell_cracked_open,_shelled,_blanched.jpg"
  },
  "prunus-laurocerasus": {
    "file": "prunus-laurocerasus.webp",
    "author": "Karduelis",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Karayemi%C5%9F-8.jpg"
  },
  "prunus-lusitanica": {
    "file": "prunus-lusitanica.webp",
    "author": "Sten Porse",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prunus-lusitanica-fruits.JPG"
  },
  "prunus-padus": {
    "file": "prunus-padus.webp",
    "author": "Игоревич",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bird_cherry_tree_1.jpg"
  },
  "prunus-persica": {
    "file": "prunus-persica.webp",
    "author": "Allagash Brewing",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peaches_at_Applecrest_Farm_Orchards_-_20108462909.jpg"
  },
  "prunus-spinosa": {
    "file": "prunus-spinosa.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Closeup_of_blackthorn_aka_sloe_aka_prunus_spinosa_sweden_20050924.jpg"
  },
  "punica-granatum": {
    "file": "punica-granatum.webp",
    "author": "H. Zell",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Punica_granatum_004.JPG"
  },
  "pyrus-bourgaeana": {
    "file": "pyrus-bourgaeana.webp",
    "author": "Bourgaeana",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flowering_Iberian_pear.jpg"
  },
  "pyrus-communis": {
    "file": "pyrus-communis.webp",
    "author": "Keith Weller",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pears.jpg"
  },
  "quercus-canariensis": {
    "file": "quercus-canariensis.webp",
    "author": "No machine-readable author provided. Carlosblh assumed (based on copyright claims).",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_canariensis.jpg"
  },
  "quercus-cerris": {
    "file": "quercus-cerris.webp",
    "author": "Giuseppe Frizzi",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dettaglio_Cupuliferae_Quercus_cerris_Lin._-_Erbario_Frizzi_Perugia_n._824.jpg"
  },
  "quercus-coccifera": {
    "file": "quercus-coccifera.webp",
    "author": "Javier martin",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_coccifera_Bellotas_2010-10-03_DehesaBoyaldePuertollano.jpg"
  },
  "quercus-coccinea": {
    "file": "quercus-coccinea.webp",
    "author": "Jay Sturner from USA",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rim_Rock_Trail_-_Scarlet_Oak_(Quercus_coccinea)_-_Flickr_-_Jay_Sturner_(2).jpg"
  },
  "quercus-faginea": {
    "file": "quercus-faginea.webp",
    "author": "No machine-readable author provided. Carlosblh assumed (based on copyright claims).",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_faginea_01.jpg"
  },
  "quercus-frainetto": {
    "file": "quercus-frainetto.webp",
    "author": "Somepics",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_frainetto_kew1.jpg"
  },
  "quercus-ilex": {
    "file": "quercus-ilex.webp",
    "author": "Fritz Geller-Grimm",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Frouzet_fg02.jpg"
  },
  "quercus-libani": {
    "file": "quercus-libani.webp",
    "author": "A. Abrahami",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_libani_port.jpg"
  },
  "quercus-lusitanica": {
    "file": "quercus-lusitanica.webp",
    "author": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_lusitanica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-253.jpg"
  },
  "quercus-palustris": {
    "file": "quercus-palustris.webp",
    "author": "Bruce Marlin",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pin_oak_quercus_palustris.jpg"
  },
  "quercus-petraea": {
    "file": "quercus-petraea.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_petraea_02.jpg"
  },
  "quercus-pubescens": {
    "file": "quercus-pubescens.webp",
    "author": "Gianni Careddu",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flora_della_Sardegna_003_(18).jpg"
  },
  "quercus-pyrenaica": {
    "file": "quercus-pyrenaica.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Melojo.jpg"
  },
  "quercus-robur": {
    "file": "quercus-robur.webp",
    "author": "Algirdas at Lithuanian Wikipedia",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paprastasis_azuolas.JPG"
  },
  "quercus-rubra": {
    "file": "quercus-rubra.webp",
    "author": "Nicholas A. Tonelli from Northeast Pennsylvania, USA",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Twin_Sisters_Trail_(14)_(14092717698).jpg"
  },
  "quercus-suber": {
    "file": "quercus-suber.webp",
    "author": "Jean-Pol GRANDMONT",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quercus_suber_JPG1.jpg"
  },
  "quercus-virginiana": {
    "file": "quercus-virginiana.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Live_oak_Georgetown.jpg"
  },
  "rhamnus-alaternus": {
    "file": "rhamnus-alaternus.webp",
    "author": "Giuseppe Frizzi",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dettaglio_-_Rhamnaceae_Rhamnus_Alaternus_Lin._Erbario_Frizzi_Perugia_n._3815.jpg"
  },
  "rhamnus-lycioides": {
    "file": "rhamnus-lycioides.webp",
    "author": "Retama",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhamnus_lycioides.jpg"
  },
  "rhus-coriaria": {
    "file": "rhus-coriaria.webp",
    "author": "Dedda71",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sommacco.jpg"
  },
  "robinia-pseudoacacia": {
    "file": "robinia-pseudoacacia.webp",
    "author": "Annabell Hormann / korina.info",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Korina_2011-05-20_Robinia_pseudoacacia_3.jpg"
  },
  "salix-alba": {
    "file": "salix-alba.webp",
    "author": "Sven Teschke",
    "license": "CC BY-SA 3.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2015-05-08_B%C3%BCdingen_Naturdenkmal_440.221_Silber-Weide_-_0919.jpg"
  },
  "salix-atrocinerea": {
    "file": "salix-atrocinerea.webp",
    "author": "BCB",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salix_cinerea_flowers-2.jpg"
  },
  "salix-babylonica": {
    "file": "salix-babylonica.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Salix_babylonica_-_Les_Martels,_Giroussens_Tarn.jpg"
  },
  "salix-caprea": {
    "file": "salix-caprea.webp",
    "author": "Kurt Stüber [1]",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salix_caprea8.jpg"
  },
  "salix-eleagnos": {
    "file": "salix-eleagnos.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salix_elaeagnos1.jpg"
  },
  "salix-fragilis": {
    "file": "salix-fragilis.webp",
    "author": "Andreas Eichler",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2015.07.07.-16-Mulde_Eilenburg--Bruch-Weide.jpg"
  },
  "salix-purpurea": {
    "file": "salix-purpurea.webp",
    "author": "Willow",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salix_purpurea_003.jpg"
  },
  "sambucus-nigra": {
    "file": "sambucus-nigra.webp",
    "author": "Willow",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sambucus_nigra_004.jpg"
  },
  "schinus-molle": {
    "file": "schinus-molle.webp",
    "author": "Charles Gadbois",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Arequipa_-_Canyon_de_Colca_123_Schinus_molle_1.JPG"
  },
  "sequoia-sempervirens": {
    "file": "sequoia-sempervirens.webp",
    "author": "Allie_Caulfield from Germany",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sequoia_sempervirens_Big_Basin_Redwoods_State_Park_9.jpg"
  },
  "sequoiadendron-giganteum": {
    "file": "sequoiadendron-giganteum.webp",
    "author": "Mike Murphy (talk · contribs)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grizzly_Giant_Mariposa_Grove.jpg"
  },
  "sorbus-aria": {
    "file": "sorbus-aria.webp",
    "author": "Julie Anne Workman",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sorbus_aria-3420.jpg"
  },
  "sorbus-aucuparia": {
    "file": "sorbus-aucuparia.webp",
    "author": "Thomas Bjørkan",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rowan_berries.JPG"
  },
  "sorbus-domestica": {
    "file": "sorbus-domestica.webp",
    "author": "Christoph Wagener",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sorbus_domestica_habit.jpg"
  },
  "sorbus-torminalis": {
    "file": "sorbus-torminalis.webp",
    "author": "Johann Daniel Reitter; Gottlieb Friedrich Abel",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Reitter-Abel_Holzarten_T020.jpg"
  },
  "spartium-junceum": {
    "file": "spartium-junceum.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spartium_junceum_(habitus).jpg"
  },
  "styphnolobium-japonicum": {
    "file": "styphnolobium-japonicum.webp",
    "author": "Jean-Pol GRANDMONT",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sophora_japonica_JPG2Aa.jpg"
  },
  "tamarix-africana": {
    "file": "tamarix-africana.webp",
    "author": "Philmarin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:T._africana-1.JPG"
  },
  "tamarix-gallica": {
    "file": "tamarix-gallica.webp",
    "author": "Javier martinlo",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tamarix_gallica_flores_ArgamasillaCalatrava.jpg"
  },
  "taxus-baccata": {
    "file": "taxus-baccata.webp",
    "author": "Sitomon",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Taxus_baccata_tree.jpg"
  },
  "tetraclinis-articulata": {
    "file": "tetraclinis-articulata.webp",
    "author": "Cs california",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tetraclinis_articulata.JPG"
  },
  "thuja-occidentalis": {
    "file": "thuja-occidentalis.webp",
    "author": "Daniel Dumais",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2013-11-06_Lac_Canards_DDumais_(21).jpg"
  },
  "tilia-cordata": {
    "file": "tilia-cordata.webp",
    "author": "ImreKiss",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tilia_cordata,_Lipa2009.jpg"
  },
  "tilia-platyphyllos": {
    "file": "tilia-platyphyllos.webp",
    "author": "Chmee2",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:L%C3%ADpa_u_Horn%C3%ADho_Z%C3%A1blat%C3%AD_v_roce_2011_(1).JPG"
  },
  "ulmus-glabra": {
    "file": "ulmus-glabra.webp",
    "author": "Ronnie Nijboer",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:RN_Ulmus_glabra_(alnarp_sweden).jpg"
  },
  "ulmus-minor": {
    "file": "ulmus-minor.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Illustration_Ulmus_carpinifolia0.jpg"
  },
  "ulmus-pumila": {
    "file": "ulmus-pumila.webp",
    "author": "Bruce Marlin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ulmus_pumila.jpg"
  },
  "viburnum-tinus": {
    "file": "viburnum-tinus.webp",
    "author": "Giuseppe Frizzi",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dettaglio_-_Caprifoliaceae_Viburnum_tinus_Lin._Erbario_Frizzi_Perugia_n._1221.jpg"
  },
  "washingtonia-robusta": {
    "file": "washingtonia-robusta.webp",
    "author": "stekkelpak",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022-02-20_Washingtonia_robusta,_Las_Flores,_Todos_Santos,_Baja_California_Sur,_Mexico.jpg"
  },
  "ziziphus-jujuba": {
    "file": "ziziphus-jujuba.webp",
    "author": "Rémi Tournebize",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jujube_n.jpg"
  }
};
